### PR TITLE
New xml file for Davis 346 Red

### PR DESCRIPTION
**Pull request by gokulbnr**
The uploaded xml file worked best with Davis346 Red sensor on my system.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
+1

**Review by tobidelbruck — CHANGES_REQUESTED** [review]
This is great!  However could we ask that the xml be stripped to remove the non Davis346red lines? The XML currently has a huge number of inherited settings from other filters that were unfortunately inhertited from previous preferences (probably from trying some other settings). More recent camera bias setting files have these extraneous settings stripped out on save but some of the older XMLs don't have this.

**Comment by tobidelbruck** [comment]
I can try to strip out the non-DAVIS config stuff, might have time later this week. Please hang on if you don't have time/knowledge to do it.

**Comment by gokulbnr** [comment]
Thanks for looking into this! 
I'm afraid I don't know what specific changes we are looking for. Would you like to get rid of configurations that don't have "Davis346red" in their key? I have been working with version 1.9.5 because it is built off the box without any errors for me. Would you recommend using a newer version of jAER? Would a newer version provide me with the required shorter-form of the configuration file on save?
I also just wanted to report how I got to this configuration. The best output I could with the given biasgenSettings had the following artifacts in its APS feed with the following feedback on the command line:
Screenshot from 2023-08-28 12-32-13
Screenshot from 2023-08-28 12-32-24
However, I could get a cleaner feed with DV (https://inivation.gitlab.io/dv/dv-docs/docs/getting-started.html) with the same sensor. Interestingly, running jAER right after running DV gave me cleaner output, and saving the config at that point on jAER provided me a file different from any I'd loaded on jAER until then.
Screenshot from 2023-08-29 12-47-13

**Comment by tobidelbruck** [comment]
That's really interesting. I have seen these APS artifcacts (rows 
corrupted) also running jAER with Davis346Blue after running in jAER. 
They are always fixed by replugging camera to USB, so there is likely 
something in USB configuration sent to camera that is getting messed up, 
but I could not figure it out. It's interesting that running camera in 
DV fixes it without replugging camera.

I will investigate it as soon as I get a chance. Don't worry I will do 
the edit to config file to strip extraneous config info not related to 
camera hardware or software settings. Unfortunately the java preferences 
are located by package (folder) and there is no simple way to isolate 
all camera settings to one folder since all DAVIS cameras use the same 
base DavisConfig class.

**Comment by gokulbnr** [comment]
I should have specified earlier. The above behavior with getting a good output on jAER after putting it through DV was observed after replugging the camera before running it with DV. Until then, just replugging the camera with the USB did not really change anything for me. Could it be because the bias configurations weren't the best? Do the artifacts (rows corrupted) show up as a result of sub-optimal biases (wrong XML file)? I did not notice a relation between replugging the camera to USB and the occurrence of the artifacts illustrated above. I'll take a look. Thanks!

**Comment by tobidelbruck** [comment]
accepted this useful pull and I will strip the stuff not related to this camera myself.

**Comment by tobidelbruck** [comment]
I stripped out the stuff not related to Davis346Red and moved to Davis346b folder in biasgenSettings

**Pull request merged**
